# This docker-compose.yml file is intended for easy development of this Docker image.
version: '3'
services:
  ghost:
    image: ghost:3
    ports:
      - 80:2368
    volumes:
      - ./content/:/var/lib/ghost/content/
    restart: always
    environment:
      - url=http://localhost
